//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("OfferAppModel", "FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(citPOINT.OfferApp.Data.Web.NegotiationOfferSetting), "ConversationOfferSetting", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.OfferApp.Data.Web.ConversationOfferSetting), true)]

#endregion

namespace citPOINT.OfferApp.Data.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OfferAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OfferAppEntities object using the connection string found in the 'OfferAppEntities' section of the application configuration file.
        /// </summary>
        public OfferAppEntities() : base("name=OfferAppEntities", "OfferAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OfferAppEntities object.
        /// </summary>
        public OfferAppEntities(string connectionString) : base(connectionString, "OfferAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OfferAppEntities object.
        /// </summary>
        public OfferAppEntities(EntityConnection connection) : base(connection, "OfferAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConversationOfferSetting> ConversationOfferSettings
        {
            get
            {
                if ((_ConversationOfferSettings == null))
                {
                    _ConversationOfferSettings = base.CreateObjectSet<ConversationOfferSetting>("ConversationOfferSettings");
                }
                return _ConversationOfferSettings;
            }
        }
        private ObjectSet<ConversationOfferSetting> _ConversationOfferSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NegotiationOfferSetting> NegotiationOfferSettings
        {
            get
            {
                if ((_NegotiationOfferSettings == null))
                {
                    _NegotiationOfferSettings = base.CreateObjectSet<NegotiationOfferSetting>("NegotiationOfferSettings");
                }
                return _NegotiationOfferSettings;
            }
        }
        private ObjectSet<NegotiationOfferSetting> _NegotiationOfferSettings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConversationOfferSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConversationOfferSettings(ConversationOfferSetting conversationOfferSetting)
        {
            base.AddObject("ConversationOfferSettings", conversationOfferSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NegotiationOfferSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNegotiationOfferSettings(NegotiationOfferSetting negotiationOfferSetting)
        {
            base.AddObject("NegotiationOfferSettings", negotiationOfferSetting);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OfferAppModel", Name="ConversationOfferSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConversationOfferSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConversationOfferSetting object.
        /// </summary>
        /// <param name="conversationOfferSettingID">Initial value of the ConversationOfferSettingID property.</param>
        /// <param name="conversationID">Initial value of the ConversationID property.</param>
        public static ConversationOfferSetting CreateConversationOfferSetting(global::System.Guid conversationOfferSettingID, global::System.Guid conversationID)
        {
            ConversationOfferSetting conversationOfferSetting = new ConversationOfferSetting();
            conversationOfferSetting.ConversationOfferSettingID = conversationOfferSettingID;
            conversationOfferSetting.ConversationID = conversationID;
            return conversationOfferSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConversationOfferSettingID
        {
            get
            {
                return _ConversationOfferSettingID;
            }
            set
            {
                if (_ConversationOfferSettingID != value)
                {
                    OnConversationOfferSettingIDChanging(value);
                    ReportPropertyChanging("ConversationOfferSettingID");
                    _ConversationOfferSettingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConversationOfferSettingID");
                    OnConversationOfferSettingIDChanged();
                }
            }
        }
        private global::System.Guid _ConversationOfferSettingID;
        partial void OnConversationOfferSettingIDChanging(global::System.Guid value);
        partial void OnConversationOfferSettingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NegotiationOfferSettingID
        {
            get
            {
                return _NegotiationOfferSettingID;
            }
            set
            {
                OnNegotiationOfferSettingIDChanging(value);
                ReportPropertyChanging("NegotiationOfferSettingID");
                _NegotiationOfferSettingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationOfferSettingID");
                OnNegotiationOfferSettingIDChanged();
            }
        }
        private Nullable<global::System.Guid> _NegotiationOfferSettingID;
        partial void OnNegotiationOfferSettingIDChanging(Nullable<global::System.Guid> value);
        partial void OnNegotiationOfferSettingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConversationID
        {
            get
            {
                return _ConversationID;
            }
            set
            {
                OnConversationIDChanging(value);
                ReportPropertyChanging("ConversationID");
                _ConversationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConversationID");
                OnConversationIDChanged();
            }
        }
        private global::System.Guid _ConversationID;
        partial void OnConversationIDChanging(global::System.Guid value);
        partial void OnConversationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BaseOfferTypeID
        {
            get
            {
                return _BaseOfferTypeID;
            }
            set
            {
                OnBaseOfferTypeIDChanging(value);
                ReportPropertyChanging("BaseOfferTypeID");
                _BaseOfferTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseOfferTypeID");
                OnBaseOfferTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BaseOfferTypeID;
        partial void OnBaseOfferTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnBaseOfferTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TargetTypeID
        {
            get
            {
                return _TargetTypeID;
            }
            set
            {
                OnTargetTypeIDChanging(value);
                ReportPropertyChanging("TargetTypeID");
                _TargetTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetTypeID");
                OnTargetTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TargetTypeID;
        partial void OnTargetTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnTargetTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TargetValue
        {
            get
            {
                return _TargetValue;
            }
            set
            {
                OnTargetValueChanging(value);
                ReportPropertyChanging("TargetValue");
                _TargetValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetValue");
                OnTargetValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TargetValue;
        partial void OnTargetValueChanging(Nullable<global::System.Decimal> value);
        partial void OnTargetValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OfferAppModel", "FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting")]
        public NegotiationOfferSetting NegotiationOfferSetting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NegotiationOfferSetting> NegotiationOfferSettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NegotiationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "NegotiationOfferSetting", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OfferAppModel", Name="NegotiationOfferSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NegotiationOfferSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NegotiationOfferSetting object.
        /// </summary>
        /// <param name="negotiationOfferSettingID">Initial value of the NegotiationOfferSettingID property.</param>
        /// <param name="negotiationID">Initial value of the NegotiationID property.</param>
        public static NegotiationOfferSetting CreateNegotiationOfferSetting(global::System.Guid negotiationOfferSettingID, global::System.Guid negotiationID)
        {
            NegotiationOfferSetting negotiationOfferSetting = new NegotiationOfferSetting();
            negotiationOfferSetting.NegotiationOfferSettingID = negotiationOfferSettingID;
            negotiationOfferSetting.NegotiationID = negotiationID;
            return negotiationOfferSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NegotiationOfferSettingID
        {
            get
            {
                return _NegotiationOfferSettingID;
            }
            set
            {
                if (_NegotiationOfferSettingID != value)
                {
                    OnNegotiationOfferSettingIDChanging(value);
                    ReportPropertyChanging("NegotiationOfferSettingID");
                    _NegotiationOfferSettingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NegotiationOfferSettingID");
                    OnNegotiationOfferSettingIDChanged();
                }
            }
        }
        private global::System.Guid _NegotiationOfferSettingID;
        partial void OnNegotiationOfferSettingIDChanging(global::System.Guid value);
        partial void OnNegotiationOfferSettingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NegotiationID
        {
            get
            {
                return _NegotiationID;
            }
            set
            {
                OnNegotiationIDChanging(value);
                ReportPropertyChanging("NegotiationID");
                _NegotiationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationID");
                OnNegotiationIDChanged();
            }
        }
        private global::System.Guid _NegotiationID;
        partial void OnNegotiationIDChanging(global::System.Guid value);
        partial void OnNegotiationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BaseOfferTypeID
        {
            get
            {
                return _BaseOfferTypeID;
            }
            set
            {
                OnBaseOfferTypeIDChanging(value);
                ReportPropertyChanging("BaseOfferTypeID");
                _BaseOfferTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseOfferTypeID");
                OnBaseOfferTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BaseOfferTypeID;
        partial void OnBaseOfferTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnBaseOfferTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TargetTypeID
        {
            get
            {
                return _TargetTypeID;
            }
            set
            {
                OnTargetTypeIDChanging(value);
                ReportPropertyChanging("TargetTypeID");
                _TargetTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetTypeID");
                OnTargetTypeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TargetTypeID;
        partial void OnTargetTypeIDChanging(Nullable<global::System.Int32> value);
        partial void OnTargetTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TargetValue
        {
            get
            {
                return _TargetValue;
            }
            set
            {
                OnTargetValueChanging(value);
                ReportPropertyChanging("TargetValue");
                _TargetValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TargetValue");
                OnTargetValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _TargetValue;
        partial void OnTargetValueChanging(Nullable<global::System.Decimal> value);
        partial void OnTargetValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OfferAppModel", "FK__Conversat__Negot__20C1E124", "ConversationOfferSetting")]
        public EntityCollection<ConversationOfferSetting> ConversationOfferSettings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConversationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "ConversationOfferSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConversationOfferSetting>("OfferAppModel.FK__Conversat__Negot__20C1E124", "ConversationOfferSetting", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
