//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citPOINT.OfferApp.Data.Web.StrategyAppService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversationStrategySetting", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class ConversationStrategySetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BetaValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ConversationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ConversationStrategySettingsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeletedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> NegotiationStrategySettingsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrategyTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BetaValue {
            get {
                return this.BetaValueField;
            }
            set {
                if ((this.BetaValueField.Equals(value) != true)) {
                    this.BetaValueField = value;
                    this.RaisePropertyChanged("BetaValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ConversationID {
            get {
                return this.ConversationIDField;
            }
            set {
                if ((this.ConversationIDField.Equals(value) != true)) {
                    this.ConversationIDField = value;
                    this.RaisePropertyChanged("ConversationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ConversationStrategySettingsID {
            get {
                return this.ConversationStrategySettingsIDField;
            }
            set {
                if ((this.ConversationStrategySettingsIDField.Equals(value) != true)) {
                    this.ConversationStrategySettingsIDField = value;
                    this.RaisePropertyChanged("ConversationStrategySettingsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((this.DeletedByField.Equals(value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeletedOn {
            get {
                return this.DeletedOnField;
            }
            set {
                if ((this.DeletedOnField.Equals(value) != true)) {
                    this.DeletedOnField = value;
                    this.RaisePropertyChanged("DeletedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> NegotiationStrategySettingsID {
            get {
                return this.NegotiationStrategySettingsIDField;
            }
            set {
                if ((this.NegotiationStrategySettingsIDField.Equals(value) != true)) {
                    this.NegotiationStrategySettingsIDField = value;
                    this.RaisePropertyChanged("NegotiationStrategySettingsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrategyTypeID {
            get {
                return this.StrategyTypeIDField;
            }
            set {
                if ((this.StrategyTypeIDField.Equals(value) != true)) {
                    this.StrategyTypeIDField = value;
                    this.RaisePropertyChanged("StrategyTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NegotiationStrategySetting", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class NegotiationStrategySetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BetaValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DefaultEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DefaultStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> DeletedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeletedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid NegotiationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid NegotiationStrategySettingsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrategyTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BetaValue {
            get {
                return this.BetaValueField;
            }
            set {
                if ((this.BetaValueField.Equals(value) != true)) {
                    this.BetaValueField = value;
                    this.RaisePropertyChanged("BetaValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DefaultEndDate {
            get {
                return this.DefaultEndDateField;
            }
            set {
                if ((this.DefaultEndDateField.Equals(value) != true)) {
                    this.DefaultEndDateField = value;
                    this.RaisePropertyChanged("DefaultEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DefaultStartDate {
            get {
                return this.DefaultStartDateField;
            }
            set {
                if ((this.DefaultStartDateField.Equals(value) != true)) {
                    this.DefaultStartDateField = value;
                    this.RaisePropertyChanged("DefaultStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Deleted {
            get {
                return this.DeletedField;
            }
            set {
                if ((this.DeletedField.Equals(value) != true)) {
                    this.DeletedField = value;
                    this.RaisePropertyChanged("Deleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DeletedBy {
            get {
                return this.DeletedByField;
            }
            set {
                if ((this.DeletedByField.Equals(value) != true)) {
                    this.DeletedByField = value;
                    this.RaisePropertyChanged("DeletedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeletedOn {
            get {
                return this.DeletedOnField;
            }
            set {
                if ((this.DeletedOnField.Equals(value) != true)) {
                    this.DeletedOnField = value;
                    this.RaisePropertyChanged("DeletedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid NegotiationID {
            get {
                return this.NegotiationIDField;
            }
            set {
                if ((this.NegotiationIDField.Equals(value) != true)) {
                    this.NegotiationIDField = value;
                    this.RaisePropertyChanged("NegotiationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid NegotiationStrategySettingsID {
            get {
                return this.NegotiationStrategySettingsIDField;
            }
            set {
                if ((this.NegotiationStrategySettingsIDField.Equals(value) != true)) {
                    this.NegotiationStrategySettingsIDField = value;
                    this.RaisePropertyChanged("NegotiationStrategySettingsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrategyTypeID {
            get {
                return this.StrategyTypeIDField;
            }
            set {
                if ((this.StrategyTypeIDField.Equals(value) != true)) {
                    this.StrategyTypeIDField = value;
                    this.RaisePropertyChanged("StrategyTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StrategyType", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class StrategyType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrategyTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrategyTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Beta {
            get {
                return this.BetaField;
            }
            set {
                if ((this.BetaField.Equals(value) != true)) {
                    this.BetaField = value;
                    this.RaisePropertyChanged("Beta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrategyTypeID {
            get {
                return this.StrategyTypeIDField;
            }
            set {
                if ((this.StrategyTypeIDField.Equals(value) != true)) {
                    this.StrategyTypeIDField = value;
                    this.RaisePropertyChanged("StrategyTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrategyTypeName {
            get {
                return this.StrategyTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StrategyTypeNameField, value) != true)) {
                    this.StrategyTypeNameField = value;
                    this.RaisePropertyChanged("StrategyTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpectedTarget", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class ExpectedTarget : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private citPOINT.OfferApp.Data.Web.StrategyAppService.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TargetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public citPOINT.OfferApp.Data.Web.StrategyAppService.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Target {
            get {
                return this.TargetField;
            }
            set {
                if ((this.TargetField.Equals(value) != true)) {
                    this.TargetField = value;
                    this.RaisePropertyChanged("Target");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateOutOfPeriod = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoSettings = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversationPeriod", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class ConversationPeriod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MaxConversationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MinConversationDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MaxConversationDate {
            get {
                return this.MaxConversationDateField;
            }
            set {
                if ((this.MaxConversationDateField.Equals(value) != true)) {
                    this.MaxConversationDateField = value;
                    this.RaisePropertyChanged("MaxConversationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MinConversationDate {
            get {
                return this.MinConversationDateField;
            }
            set {
                if ((this.MinConversationDateField.Equals(value) != true)) {
                    this.MinConversationDateField = value;
                    this.RaisePropertyChanged("MinConversationDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreferenceSet", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class PreferenceSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MaxPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid PreferenceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxPercentage {
            get {
                return this.MaxPercentageField;
            }
            set {
                if ((this.MaxPercentageField.Equals(value) != true)) {
                    this.MaxPercentageField = value;
                    this.RaisePropertyChanged("MaxPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PreferenceID {
            get {
                return this.PreferenceIDField;
            }
            set {
                if ((this.PreferenceIDField.Equals(value) != true)) {
                    this.PreferenceIDField = value;
                    this.RaisePropertyChanged("PreferenceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LastOfferDetails", Namespace="http://schemas.datacontract.org/2004/07/citPOINT.StrategyApp.Data.Web")]
    [System.SerializableAttribute()]
    public partial class LastOfferDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OfferDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercentageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OfferDate {
            get {
                return this.OfferDateField;
            }
            set {
                if ((this.OfferDateField.Equals(value) != true)) {
                    this.OfferDateField = value;
                    this.RaisePropertyChanged("OfferDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Percentage {
            get {
                return this.PercentageField;
            }
            set {
                if ((this.PercentageField.Equals(value) != true)) {
                    this.PercentageField = value;
                    this.RaisePropertyChanged("Percentage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StrategyAppService.StrategyAppServiceSoap")]
    public interface StrategyAppServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettings", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettingsResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettingsDomainSe" +
            "rviceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting> GetConversationStrategySettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettings", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettingsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettingsDomainSer" +
            "viceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting> GetNegotiationStrategySettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetStrategyTypes", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetStrategyTypesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetStrategyTypesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType> GetStrategyTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForNegotiation", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForNegotiationResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForNegotiationDoma" +
            "inServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget> GetNextExpectedTargetForNegotiation(System.Guid negotiationID, decimal maxPercentage, System.DateTime currentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForConversation", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForConversationRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetNextExpectedTargetForConversationDom" +
            "ainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget> GetNextExpectedTargetForConversation(System.Guid negotiationID, System.Guid conversationID, decimal maxPercentage, System.DateTime currentDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettingsByNegID", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettingsByNegIDRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationStrategySettingsByNegIDDo" +
            "mainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting> GetNegotiationStrategySettingsByNegID(System.Guid negotiationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationPeriod", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationPeriodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetNegotiationPeriodDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod> GetNegotiationPeriod(System.Guid negotiationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettingsByConvID" +
            "", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettingsByConvID" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationStrategySettingsByConvID" +
            "DomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting> GetConversationStrategySettingsByConvID(System.Guid conversationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationPeriod", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetConversationPeriodResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetConversationPeriodDomainServiceFault" +
            "", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod> GetConversationPeriod(System.Guid conversationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetPreferenceSetForNegotiation", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetPreferenceSetForNegotiationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetPreferenceSetForNegotiationDomainSer" +
            "viceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet> GetPreferenceSetForNegotiation(System.Guid negotiationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/GetLastOfferForConversation", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/GetLastOfferForConversationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/GetLastOfferForConversationDomainServic" +
            "eFault", Name="DomainServiceFault", Namespace="DomainServices")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.Status))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(int[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ValidationResultInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.ChangeSetEntry))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.DomainServices.Server.DomainOperation))]
        System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails> GetLastOfferForConversation(System.Guid conversationID, bool isSent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StrategyAppServiceSoap/SubmitChanges", ReplyAction="http://tempuri.org/StrategyAppServiceSoap/SubmitChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.DomainServices.Hosting.DomainServiceFault), Action="http://tempuri.org/StrategyAppServiceSoap/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.ServiceModel.DomainServices.Server.ChangeSetEntry[] SubmitChanges(System.ServiceModel.DomainServices.Server.ChangeSetEntry[] changeSet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StrategyAppServiceSoapChannel : citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyAppServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrategyAppServiceSoapClient : System.ServiceModel.ClientBase<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyAppServiceSoap>, citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyAppServiceSoap {
        
        public StrategyAppServiceSoapClient() {
        }
        
        public StrategyAppServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrategyAppServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrategyAppServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrategyAppServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting> GetConversationStrategySettings() {
            return base.Channel.GetConversationStrategySettings();
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting> GetNegotiationStrategySettings() {
            return base.Channel.GetNegotiationStrategySettings();
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.StrategyType> GetStrategyTypes() {
            return base.Channel.GetStrategyTypes();
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget> GetNextExpectedTargetForNegotiation(System.Guid negotiationID, decimal maxPercentage, System.DateTime currentDate) {
            return base.Channel.GetNextExpectedTargetForNegotiation(negotiationID, maxPercentage, currentDate);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ExpectedTarget> GetNextExpectedTargetForConversation(System.Guid negotiationID, System.Guid conversationID, decimal maxPercentage, System.DateTime currentDate) {
            return base.Channel.GetNextExpectedTargetForConversation(negotiationID, conversationID, maxPercentage, currentDate);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.NegotiationStrategySetting> GetNegotiationStrategySettingsByNegID(System.Guid negotiationID) {
            return base.Channel.GetNegotiationStrategySettingsByNegID(negotiationID);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod> GetNegotiationPeriod(System.Guid negotiationID) {
            return base.Channel.GetNegotiationPeriod(negotiationID);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationStrategySetting> GetConversationStrategySettingsByConvID(System.Guid conversationID) {
            return base.Channel.GetConversationStrategySettingsByConvID(conversationID);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.ConversationPeriod> GetConversationPeriod(System.Guid conversationID) {
            return base.Channel.GetConversationPeriod(conversationID);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.PreferenceSet> GetPreferenceSetForNegotiation(System.Guid negotiationID) {
            return base.Channel.GetPreferenceSetForNegotiation(negotiationID);
        }
        
        public System.ServiceModel.DomainServices.Hosting.QueryResult<citPOINT.OfferApp.Data.Web.StrategyAppService.LastOfferDetails> GetLastOfferForConversation(System.Guid conversationID, bool isSent) {
            return base.Channel.GetLastOfferForConversation(conversationID, isSent);
        }
        
        public System.ServiceModel.DomainServices.Server.ChangeSetEntry[] SubmitChanges(System.ServiceModel.DomainServices.Server.ChangeSetEntry[] changeSet) {
            return base.Channel.SubmitChanges(changeSet);
        }
    }
}
